#!/usr/bin/bash

tar xvzf libgpg-error-1.31.tar.gz && cd libgpg-error-1.31
./configure --prefix=/usr; make; make install
cd ..

tar xvzf libgcrypt-1.8.3.tar.gz && cd libgcrypt-1.8.3
./configure --prefix=/usr; make; make install
cd ..

tar xvf libassuan-2.5.1.tar.bz2 && cd libassuan-2.5.1
./configure --prefix=/usr; make; make install
cd ..

tar xvf libksba-1.3.5.tar.bz2 && cd libksba-1.3.5
./configure --prefix=/usr; make; make install
cd ..

tar xvf npth-1.5.tar.bz2 && cd npth-1.5
./configure --prefix=/usr; make; make install
cd ..

tar xvf gnupg-2.2.8.tar.bz2 && cd gnupg-2.2.8
./configure --prefix=/usr; make; make install
cd ..

unzip libcap-master.zip && cd libcap-master
make && make install
cd ..

tar xvzf lxc-master.tar.gz && cd lxc-master
./autogen.sh; ./configure --prefix=/usr; make; make install
cd ..

tar xvzf rsync-3.1.3.tar.gz && cd rsync-3.1.3
./configure --prefix=/usr; make; make install
cd ..
